package com.smartpark.backendapi.model;

import jakarta.persistence.*;

/**
 * Represents a reservation made by a user for a parking lot.
 *
 * This entity is used to persist reservation data in the database,
 * replacing the previous in-memory tracking system.
 *
 * Each reservation links a user to a specific parking lot.
 */
@Entity
public class Reservation {


    // Unique identifier for each reservation (auto-generated by MySQL)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Username of the user who made the reservation
    private String username;


    // Role of the user (STUDENT, FACULTY, ADMIN)
    @Enumerated(EnumType.STRING)
    private UserRole userRole;

    /**
     * The parking lot associated with this reservation
     * Many reservations can reference one parking lot
     */
    @ManyToOne
    @JoinColumn(name = "parking_lot_id", nullable = false)
    private ParkingLot parkingLot;


    // Default constructor
    public Reservation() {}


    //  Constructor used when creating a new reservation
    public Reservation(String username, UserRole userRole, ParkingLot parkingLot) {
        this.username = username;
        this.userRole = userRole;
        this.parkingLot = parkingLot;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public UserRole getUserRole() {
        return userRole;
    }

    public ParkingLot getParkingLot() {
        return parkingLot;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    public void setParkingLot(ParkingLot parkingLot) {
        this.parkingLot = parkingLot;
    }
}